export default class RequestCompanies {
    id;
    company_code;
    company_name;
    company_alias;
    address;
    province_id=null;
    city_id=null;
    district_id=null;
    village_id=null;
    business_id=null;
    postal_code;
    billing_address;
    phone_number;
    email;
    contact_person;
    contact_number;
    invoice_pic=null;
    npwp_no;
    siup_no;
    npwp_path;
    siup_path;
    image;
    coordinate;
    status='ACTIVE';
}